import dayjs from "dayjs";
import { v4 as uuidv4 } from "uuid";

export const OrderList: IOrderList[] = [
  {
    id: 1,
    orderNo: dayjs().format("YYYYMMDD") + 1,
    userName: "张三",
    goodsName: "无线蓝牙耳机",
    goodsPrice: 199.9,
    goodsDesc: "高品质降噪耳机，支持快充",
    goodsCount: 2,
    payType: "支付宝",
    deliveryType: "快递配送",
    deliveryTime: "2025-07-12",
    createTime: "2025-07-09",
  },
  {
    id: 2,
    orderNo: dayjs().format("YYYYMMDD") + 2,
    userName: "李四",
    goodsName: "机械键盘",
    goodsPrice: 499.0,
    goodsDesc: "RGB背光，静音机械轴设计",
    goodsCount: 1,
    payType: "微信支付",
    deliveryType: "自提",
    deliveryTime: "2025-07-10",
    createTime: "2025-07-08",
  },
  {
    id: 3,
    orderNo: dayjs().format("YYYYMMDD") + 3,
    userName: "王五",
    goodsName: "智能手表",
    goodsPrice: 899.5,
    goodsDesc: "支持心率监测和运动追踪",
    goodsCount: 3,
    payType: "信用卡",
    deliveryType: "顺丰速运",
    deliveryTime: "2025-07-13",
    createTime: "2025-07-07",
  },
  {
    id: 4,
    orderNo: dayjs().format("YYYYMMDD") + 4,
    userName: "赵六",
    goodsName: "保温杯",
    goodsPrice: 79.9,
    goodsDesc: "双层不锈钢，保热保冷",
    goodsCount: 5,
    payType: "余额支付",
    deliveryType: "普通快递",
    deliveryTime: "2025-07-14",
    createTime: "2025-07-06",
  },
  {
    id: 5,
    orderNo: dayjs().format("YYYYMMDD") + 5,
    userName: "孙七",
    goodsName: "笔记本电脑",
    goodsPrice: 8999.0,
    goodsDesc: "高性能游戏本，RTX显卡",
    goodsCount: 1,
    payType: "花呗分期",
    deliveryType: "京东物流",
    deliveryTime: "2025-07-15",
    createTime: "2025-07-05",
  },
  {
    id: 6,
    orderNo: dayjs().format("YYYYMMDD") + 6,
    userName: "周八",
    goodsName: "电动牙刷",
    goodsPrice: 149.0,
    goodsDesc: "声波震动，防水设计",
    goodsCount: 2,
    payType: "银联云闪付",
    deliveryType: "快递配送",
    deliveryTime: "2025-07-11",
    createTime: "2025-07-04",
  },
  {
    id: 7,
    orderNo: dayjs().format("YYYYMMDD") + 7,
    userName: "吴九",
    goodsName: "空气净化器",
    goodsPrice: 699.9,
    goodsDesc: "高效过滤PM2.5，静音运行",
    goodsCount: 1,
    payType: "支付宝",
    deliveryType: "顺丰次日达",
    deliveryTime: "2025-07-10",
    createTime: "2025-07-03",
  },
  {
    id: 8,
    orderNo: dayjs().format("YYYYMMDD") + 8,
    userName: "郑十",
    goodsName: "手机充电宝",
    goodsPrice: 129.9,
    goodsDesc: "大容量，支持快充",
    goodsCount: 4,
    payType: "微信支付",
    deliveryType: "普通快递",
    deliveryTime: "2025-07-12",
    createTime: "2025-07-02",
  },
  {
    id: 9,
    orderNo: dayjs().format("YYYYMMDD") + 9,
    userName: "陈十一",
    goodsName: "折叠自行车",
    goodsPrice: 1299.0,
    goodsDesc: "轻便铝合金车身",
    goodsCount: 1,
    payType: "信用卡",
    deliveryType: "京东物流",
    deliveryTime: "2025-07-13",
    createTime: "2025-07-01",
  },
  {
    id: 10,
    orderNo: dayjs().format("YYYYMMDD") + 10,
    userName: "黄十二",
    goodsName: "加湿器",
    goodsPrice: 89.5,
    goodsDesc: "USB供电，静音雾化",
    goodsCount: 3,
    payType: "余额支付",
    deliveryType: "快递配送",
    deliveryTime: "2025-07-14",
    createTime: "2025-06-30",
  },
];
